mode: MainLine
branches:
  master:
    regex: ^master
    mode: ContinuousDelivery
    is-release-branch: false
    is-mainline: false
  release:
    regex: ^releases?[/-]
    tag: ''
    is-mainline: true
    is-release-branch: true